---
- name: Install package 
  hosts: all
  
  tasks:
  
    - name: Install package selected
      yum:
        name: "{{ package }}"
        state: installed
      register: package_result
      
    - name: Show package installed
      debug:
        var: package_result
